events { }

http {
    # Перенаправление HTTP на HTTPS
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # HTTPS сервер
    server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location /webhook {
            proxy_pass http://bot:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://bot:3001;
            proxy_set_header Host $host;
        }

        location / {
            return 200 "OK";
        }
    }
}